name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - 'docs/**'
      - 'etc/jreleaser/changelog.md.tpl'
      - 'bin/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - 'docs/**'
      - 'etc/jreleaser/changelog.md.tpl'
      - 'bin/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: ./mvnw -B clean verify --file pom.xml
